server:
  port: 8891
  tomcat:
    uri-encoding: UTF-8

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  messages:
    encoding: UTF-8
  springfox:
    documentation:
      swagger-ui:
        enabled: true
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher


